// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IFirstEntrySystem {
  function getRandomIndex(uint256 arrayLength) external returns (uint256);

  function createStory() external;
}
