// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { ProposedEntryData } from "./../systems/ProposeEntrySystem.sol";

interface IProposeEntrySystem {
  function proposeEntry(bytes32 parentKey, string memory entry) external returns (string memory);

  function vote(bytes32 proposedEntryKey) external returns (bool);

  function countVotes(bytes32 parentKey) external returns (ProposedEntryData memory);
}
