// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IProposeEntrySystem {
  function proposeEntry(string memory entry) external returns (string memory);
}
