// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ITimingSystem {
  function setProposalTime(bytes32 parentKey) external returns (uint256);

  function setVotingTime(bytes32 parentKey) external returns (uint256);

  function getCurrentlyVoting(bytes32 parentKey) external returns (bool);

  function getCurrentlyProposing(bytes32 parentKey) external returns (bool);
}
