// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IVoteSystem {
  function vote(string memory entry) external returns (string memory);
}
