// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IWriteSystem {
  function append() external returns (string memory);

  function addEntry(string memory sentence) external returns (string memory);
}
