/* Autogenerated file. Do not edit manually. */

import { TableId } from "@latticexyz/utils";
import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    Entry: (() => {
      const tableId = new TableId("", "entry");
      return defineComponent(
        world,
        {
          parent: RecsType.String,
          proposer: RecsType.String,
          sentence: RecsType.String,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    ProposedEntry: (() => {
      const tableId = new TableId("", "proposedentry");
      return defineComponent(
        world,
        {
          id: RecsType.BigInt,
          storyId: RecsType.BigInt,
          parentBlock: RecsType.BigInt,
          proposedOnBlock: RecsType.BigInt,
          timestamp: RecsType.BigInt,
          proposer: RecsType.String,
          sentence: RecsType.String,
          votes: RecsType.StringArray,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    EntryPeriod: (() => {
      const tableId = new TableId("", "entryperiod");
      return defineComponent(
        world,
        {
          id: RecsType.BigInt,
          parentBlock: RecsType.BigInt,
          periodEndsBlock: RecsType.BigInt,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    VotePeriod: (() => {
      const tableId = new TableId("", "voteperiod");
      return defineComponent(
        world,
        {
          id: RecsType.BigInt,
          parentBlock: RecsType.BigInt,
          periodEndsBlock: RecsType.BigInt,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
  };
}
