/* Autogenerated file. Do not edit manually. */

import { TableId } from "@latticexyz/utils";
import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    Story: (() => {
      const tableId = new TableId("", "story");
      return defineComponent(
        world,
        {
          archived: RecsType.Boolean,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Entry: (() => {
      const tableId = new TableId("", "entry");
      return defineComponent(
        world,
        {
          parent: RecsType.String,
          proposer: RecsType.String,
          sentence: RecsType.String,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    ParentStory: (() => {
      const tableId = new TableId("", "parentstory");
      return defineComponent(
        world,
        {
          parentKey: RecsType.String,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    ProposedEntry: (() => {
      const tableId = new TableId("", "proposedentry");
      return defineComponent(
        world,
        {
          parentKey: RecsType.String,
          proposedOnBlock: RecsType.BigInt,
          timestamp: RecsType.BigInt,
          proposer: RecsType.String,
          sentence: RecsType.String,
          votes: RecsType.StringArray,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    ParentEntry: (() => {
      const tableId = new TableId("", "parententry");
      return defineComponent(
        world,
        {
          parentKey: RecsType.String,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    ProposalPeriod: (() => {
      const tableId = new TableId("", "proposalperiod");
      return defineComponent(
        world,
        {
          periodEndsBlock: RecsType.BigInt,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
  };
}
