// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Name, NameTableId } from "./tables/Name.sol";
import { Counter, CounterTableId } from "./tables/Counter.sol";
import { GameConfig, GameConfigData, GameConfigTableId } from "./tables/GameConfig.sol";
import { Story, StoryData, StoryTableId } from "./tables/Story.sol";
import { Entry, EntryData, EntryTableId } from "./tables/Entry.sol";
import { ParentStory, ParentStoryTableId } from "./tables/ParentStory.sol";
import { ProposedEntry, ProposedEntryData, ProposedEntryTableId } from "./tables/ProposedEntry.sol";
import { ParentEntry, ParentEntryTableId } from "./tables/ParentEntry.sol";
import { ProposalPeriod, ProposalPeriodTableId } from "./tables/ProposalPeriod.sol";
