// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

uint256 constant _tableId = uint256(bytes32(abi.encodePacked(bytes16(""), bytes16("proposedentry"))));
uint256 constant ProposedEntryTableId = _tableId;

struct ProposedEntryData {
  uint256 id;
  uint256 storyId;
  uint256 parentBlock;
  uint256 proposedOnBlock;
  uint256 timestamp;
  address proposer;
  string sentence;
  address[] votes;
}

library ProposedEntry {
  /** Get the table's schema */
  function getSchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](8);
    _schema[0] = SchemaType.UINT256;
    _schema[1] = SchemaType.UINT256;
    _schema[2] = SchemaType.UINT256;
    _schema[3] = SchemaType.UINT256;
    _schema[4] = SchemaType.UINT256;
    _schema[5] = SchemaType.ADDRESS;
    _schema[6] = SchemaType.STRING;
    _schema[7] = SchemaType.ADDRESS_ARRAY;

    return SchemaLib.encode(_schema);
  }

  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](1);
    _schema[0] = SchemaType.BYTES32;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's metadata */
  function getMetadata() internal pure returns (string memory, string[] memory) {
    string[] memory _fieldNames = new string[](8);
    _fieldNames[0] = "id";
    _fieldNames[1] = "storyId";
    _fieldNames[2] = "parentBlock";
    _fieldNames[3] = "proposedOnBlock";
    _fieldNames[4] = "timestamp";
    _fieldNames[5] = "proposer";
    _fieldNames[6] = "sentence";
    _fieldNames[7] = "votes";
    return ("ProposedEntry", _fieldNames);
  }

  /** Register the table's schema */
  function registerSchema() internal {
    StoreSwitch.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Register the table's schema (using the specified store) */
  function registerSchema(IStore _store) internal {
    _store.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Set the table's metadata */
  function setMetadata() internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    StoreSwitch.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Set the table's metadata (using the specified store) */
  function setMetadata(IStore _store) internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    _store.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Get id */
  function getId(bytes32 key) internal view returns (uint256 id) {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    bytes memory _blob = StoreSwitch.getField(_tableId, _primaryKeys, 0);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Get id (using the specified store) */
  function getId(IStore _store, bytes32 key) internal view returns (uint256 id) {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    bytes memory _blob = _store.getField(_tableId, _primaryKeys, 0);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set id */
  function setId(bytes32 key, uint256 id) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    StoreSwitch.setField(_tableId, _primaryKeys, 0, abi.encodePacked((id)));
  }

  /** Set id (using the specified store) */
  function setId(IStore _store, bytes32 key, uint256 id) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    _store.setField(_tableId, _primaryKeys, 0, abi.encodePacked((id)));
  }

  /** Get storyId */
  function getStoryId(bytes32 key) internal view returns (uint256 storyId) {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    bytes memory _blob = StoreSwitch.getField(_tableId, _primaryKeys, 1);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Get storyId (using the specified store) */
  function getStoryId(IStore _store, bytes32 key) internal view returns (uint256 storyId) {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    bytes memory _blob = _store.getField(_tableId, _primaryKeys, 1);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set storyId */
  function setStoryId(bytes32 key, uint256 storyId) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    StoreSwitch.setField(_tableId, _primaryKeys, 1, abi.encodePacked((storyId)));
  }

  /** Set storyId (using the specified store) */
  function setStoryId(IStore _store, bytes32 key, uint256 storyId) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    _store.setField(_tableId, _primaryKeys, 1, abi.encodePacked((storyId)));
  }

  /** Get parentBlock */
  function getParentBlock(bytes32 key) internal view returns (uint256 parentBlock) {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    bytes memory _blob = StoreSwitch.getField(_tableId, _primaryKeys, 2);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Get parentBlock (using the specified store) */
  function getParentBlock(IStore _store, bytes32 key) internal view returns (uint256 parentBlock) {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    bytes memory _blob = _store.getField(_tableId, _primaryKeys, 2);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set parentBlock */
  function setParentBlock(bytes32 key, uint256 parentBlock) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    StoreSwitch.setField(_tableId, _primaryKeys, 2, abi.encodePacked((parentBlock)));
  }

  /** Set parentBlock (using the specified store) */
  function setParentBlock(IStore _store, bytes32 key, uint256 parentBlock) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    _store.setField(_tableId, _primaryKeys, 2, abi.encodePacked((parentBlock)));
  }

  /** Get proposedOnBlock */
  function getProposedOnBlock(bytes32 key) internal view returns (uint256 proposedOnBlock) {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    bytes memory _blob = StoreSwitch.getField(_tableId, _primaryKeys, 3);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Get proposedOnBlock (using the specified store) */
  function getProposedOnBlock(IStore _store, bytes32 key) internal view returns (uint256 proposedOnBlock) {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    bytes memory _blob = _store.getField(_tableId, _primaryKeys, 3);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set proposedOnBlock */
  function setProposedOnBlock(bytes32 key, uint256 proposedOnBlock) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    StoreSwitch.setField(_tableId, _primaryKeys, 3, abi.encodePacked((proposedOnBlock)));
  }

  /** Set proposedOnBlock (using the specified store) */
  function setProposedOnBlock(IStore _store, bytes32 key, uint256 proposedOnBlock) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    _store.setField(_tableId, _primaryKeys, 3, abi.encodePacked((proposedOnBlock)));
  }

  /** Get timestamp */
  function getTimestamp(bytes32 key) internal view returns (uint256 timestamp) {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    bytes memory _blob = StoreSwitch.getField(_tableId, _primaryKeys, 4);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Get timestamp (using the specified store) */
  function getTimestamp(IStore _store, bytes32 key) internal view returns (uint256 timestamp) {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    bytes memory _blob = _store.getField(_tableId, _primaryKeys, 4);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set timestamp */
  function setTimestamp(bytes32 key, uint256 timestamp) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    StoreSwitch.setField(_tableId, _primaryKeys, 4, abi.encodePacked((timestamp)));
  }

  /** Set timestamp (using the specified store) */
  function setTimestamp(IStore _store, bytes32 key, uint256 timestamp) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    _store.setField(_tableId, _primaryKeys, 4, abi.encodePacked((timestamp)));
  }

  /** Get proposer */
  function getProposer(bytes32 key) internal view returns (address proposer) {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    bytes memory _blob = StoreSwitch.getField(_tableId, _primaryKeys, 5);
    return (address(Bytes.slice20(_blob, 0)));
  }

  /** Get proposer (using the specified store) */
  function getProposer(IStore _store, bytes32 key) internal view returns (address proposer) {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    bytes memory _blob = _store.getField(_tableId, _primaryKeys, 5);
    return (address(Bytes.slice20(_blob, 0)));
  }

  /** Set proposer */
  function setProposer(bytes32 key, address proposer) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    StoreSwitch.setField(_tableId, _primaryKeys, 5, abi.encodePacked((proposer)));
  }

  /** Set proposer (using the specified store) */
  function setProposer(IStore _store, bytes32 key, address proposer) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    _store.setField(_tableId, _primaryKeys, 5, abi.encodePacked((proposer)));
  }

  /** Get sentence */
  function getSentence(bytes32 key) internal view returns (string memory sentence) {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    bytes memory _blob = StoreSwitch.getField(_tableId, _primaryKeys, 6);
    return (string(_blob));
  }

  /** Get sentence (using the specified store) */
  function getSentence(IStore _store, bytes32 key) internal view returns (string memory sentence) {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    bytes memory _blob = _store.getField(_tableId, _primaryKeys, 6);
    return (string(_blob));
  }

  /** Set sentence */
  function setSentence(bytes32 key, string memory sentence) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    StoreSwitch.setField(_tableId, _primaryKeys, 6, bytes((sentence)));
  }

  /** Set sentence (using the specified store) */
  function setSentence(IStore _store, bytes32 key, string memory sentence) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    _store.setField(_tableId, _primaryKeys, 6, bytes((sentence)));
  }

  /** Push a slice to sentence */
  function pushSentence(bytes32 key, string memory _slice) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    StoreSwitch.pushToField(_tableId, _primaryKeys, 6, bytes((_slice)));
  }

  /** Push a slice to sentence (using the specified store) */
  function pushSentence(IStore _store, bytes32 key, string memory _slice) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    _store.pushToField(_tableId, _primaryKeys, 6, bytes((_slice)));
  }

  /** Get votes */
  function getVotes(bytes32 key) internal view returns (address[] memory votes) {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    bytes memory _blob = StoreSwitch.getField(_tableId, _primaryKeys, 7);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_address());
  }

  /** Get votes (using the specified store) */
  function getVotes(IStore _store, bytes32 key) internal view returns (address[] memory votes) {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    bytes memory _blob = _store.getField(_tableId, _primaryKeys, 7);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_address());
  }

  /** Set votes */
  function setVotes(bytes32 key, address[] memory votes) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    StoreSwitch.setField(_tableId, _primaryKeys, 7, EncodeArray.encode((votes)));
  }

  /** Set votes (using the specified store) */
  function setVotes(IStore _store, bytes32 key, address[] memory votes) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    _store.setField(_tableId, _primaryKeys, 7, EncodeArray.encode((votes)));
  }

  /** Push an element to votes */
  function pushVotes(bytes32 key, address _element) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    StoreSwitch.pushToField(_tableId, _primaryKeys, 7, abi.encodePacked((_element)));
  }

  /** Push an element to votes (using the specified store) */
  function pushVotes(IStore _store, bytes32 key, address _element) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    _store.pushToField(_tableId, _primaryKeys, 7, abi.encodePacked((_element)));
  }

  /** Get the full data */
  function get(bytes32 key) internal view returns (ProposedEntryData memory _table) {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    bytes memory _blob = StoreSwitch.getRecord(_tableId, _primaryKeys, getSchema());
    return decode(_blob);
  }

  /** Get the full data (using the specified store) */
  function get(IStore _store, bytes32 key) internal view returns (ProposedEntryData memory _table) {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    bytes memory _blob = _store.getRecord(_tableId, _primaryKeys, getSchema());
    return decode(_blob);
  }

  /** Set the full data using individual values */
  function set(
    bytes32 key,
    uint256 id,
    uint256 storyId,
    uint256 parentBlock,
    uint256 proposedOnBlock,
    uint256 timestamp,
    address proposer,
    string memory sentence,
    address[] memory votes
  ) internal {
    bytes memory _data = encode(id, storyId, parentBlock, proposedOnBlock, timestamp, proposer, sentence, votes);

    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    StoreSwitch.setRecord(_tableId, _primaryKeys, _data);
  }

  /** Set the full data using individual values (using the specified store) */
  function set(
    IStore _store,
    bytes32 key,
    uint256 id,
    uint256 storyId,
    uint256 parentBlock,
    uint256 proposedOnBlock,
    uint256 timestamp,
    address proposer,
    string memory sentence,
    address[] memory votes
  ) internal {
    bytes memory _data = encode(id, storyId, parentBlock, proposedOnBlock, timestamp, proposer, sentence, votes);

    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    _store.setRecord(_tableId, _primaryKeys, _data);
  }

  /** Set the full data using the data struct */
  function set(bytes32 key, ProposedEntryData memory _table) internal {
    set(
      key,
      _table.id,
      _table.storyId,
      _table.parentBlock,
      _table.proposedOnBlock,
      _table.timestamp,
      _table.proposer,
      _table.sentence,
      _table.votes
    );
  }

  /** Set the full data using the data struct (using the specified store) */
  function set(IStore _store, bytes32 key, ProposedEntryData memory _table) internal {
    set(
      _store,
      key,
      _table.id,
      _table.storyId,
      _table.parentBlock,
      _table.proposedOnBlock,
      _table.timestamp,
      _table.proposer,
      _table.sentence,
      _table.votes
    );
  }

  /** Decode the tightly packed blob using this table's schema */
  function decode(bytes memory _blob) internal view returns (ProposedEntryData memory _table) {
    // 180 is the total byte length of static data
    PackedCounter _encodedLengths = PackedCounter.wrap(Bytes.slice32(_blob, 180));

    _table.id = (uint256(Bytes.slice32(_blob, 0)));

    _table.storyId = (uint256(Bytes.slice32(_blob, 32)));

    _table.parentBlock = (uint256(Bytes.slice32(_blob, 64)));

    _table.proposedOnBlock = (uint256(Bytes.slice32(_blob, 96)));

    _table.timestamp = (uint256(Bytes.slice32(_blob, 128)));

    _table.proposer = (address(Bytes.slice20(_blob, 160)));

    uint256 _start;
    uint256 _end = 212;

    _start = _end;
    _end += _encodedLengths.atIndex(0);
    _table.sentence = (string(SliceLib.getSubslice(_blob, _start, _end).toBytes()));

    _start = _end;
    _end += _encodedLengths.atIndex(1);
    _table.votes = (SliceLib.getSubslice(_blob, _start, _end).decodeArray_address());
  }

  /** Tightly pack full data using this table's schema */
  function encode(
    uint256 id,
    uint256 storyId,
    uint256 parentBlock,
    uint256 proposedOnBlock,
    uint256 timestamp,
    address proposer,
    string memory sentence,
    address[] memory votes
  ) internal view returns (bytes memory) {
    uint16[] memory _counters = new uint16[](2);
    _counters[0] = uint16(bytes(sentence).length);
    _counters[1] = uint16(votes.length * 20);
    PackedCounter _encodedLengths = PackedCounterLib.pack(_counters);

    return
      abi.encodePacked(
        id,
        storyId,
        parentBlock,
        proposedOnBlock,
        timestamp,
        proposer,
        _encodedLengths.unwrap(),
        bytes((sentence)),
        EncodeArray.encode((votes))
      );
  }

  /* Delete all data for given keys */
  function deleteRecord(bytes32 key) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    StoreSwitch.deleteRecord(_tableId, _primaryKeys);
  }

  /* Delete all data for given keys (using the specified store) */
  function deleteRecord(IStore _store, bytes32 key) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32((key));

    _store.deleteRecord(_tableId, _primaryKeys);
  }
}
