// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IFirstEntrySystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IFirstEntrySystem {
  function mud_FirstEntrySystem_getRandomIndex(uint256 arrayLength) external view returns (uint256);

  function mud_FirstEntrySystem_createStory() external;
}
