// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IProposalsSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IProposalsSystem {
  function mud_ProposalsSystem_proposeEntry(bytes32 parentKey, string memory entry) external returns (string memory);

  function mud_ProposalsSystem_vote(bytes32 proposedEntryKey) external returns (bool);

  function mud_ProposalsSystem_countVotes(bytes32 parentKey) external;
}
