// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IProposeEntrySystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IProposeEntrySystem {
  function mud_ProposeEntrySyst_proposeEntry(bytes32 parentKey, string memory entry) external returns (string memory);

  function mud_ProposeEntrySyst_vote(bytes32 proposedEntryKey) external returns (bool);

  function mud_ProposeEntrySyst_countVotes(bytes32 parentKey) external;
}
