// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ISpawnSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ISpawnSystem {
  function mud_SpawnSystem_spawn(string memory _name) external returns (bytes32);
}
