// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ITimingSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITimingSystem {
  function mud_TimingSystem_setProposalTime(bytes32 parentKey) external returns (uint256);

  function mud_TimingSystem_getCurrentlyActive(bytes32 parentKey) external view returns (bool);
}
